### ISSUE TITLE
Fix alias parsing and release fixed database

### ISSUE THREAD

**Issue by reece** [biocommons/biocommons.seqrepo#76]
Something changed last year in a way that caused the entire defline to be loaded as an alias. seqrepo releases since last June or so are affected. This affects NCBI and Ensembl.
~See comments in `cli.py::load()`~

This issue is a master list for work to comprehensively fix parsing. It will need to span several package and data releases.

### 0.5.5
- [x] Move defline parsing to separate fx and add tests (#78)
- [x] Create mechanism to modify/fix existing databases in place (#79)
- [x] Require `Ensembl` aliases to have a version and remove unversioned from db (#80)
- [x] Reject whitespace in aliases and fix existing db (#83)
- [x] Drop support for `gi` and `genbank` and remove from db (#81)
- [ ] Release a new snapshot with the above fixes
